server:
  port: 0
spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
       routes:
       - id: Washer-Service
         uri: http://localhost:8082/
         predicates:
         - Path=/washer/**
       - id: Admin-Service
         uri: http://localhost:8083/
         predicates:
         - Path=/admin/**
      
